-- =====================================================
-- POS System Database Schema
-- SQLite Database (Auto-created by config.php)
-- =====================================================
--
-- This file is kept for reference only.
-- The database is automatically created by config.php
-- on first API access.
--
-- To reset: Just delete api/database.sqlite
-- It will be recreated automatically.
--
-- Default login: admin@konok.io / @rsm@k@1A
-- =====================================================
